REFRESH_INTERVAL = 60 * 60 * 24  # 1 day

STOCKS_DATA_INTERVAL = "1d"
STOCKS_DATA_PERIOD = "5y"
STOCKS_NUM_PREDICTIONS = (
    24 * 7
)  # 1 week (NOTE: This depends on the `STOCKS_DATA_INTERVAL`)
NUM_STOCKS_TO_MONITOR = 10